# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2665ab4cd81392b37f092760db72c46d243bcfe153cea0909aa3c9d2a744fbd926e474bdd3856ca821aaea5a7e5c9ea33b581e8fa777bd362bcea13d737639c3

test:
  secret_key_base: 0e14f42746fae4c1cc7326a28b617214bea51a9c9e946d29106a335e7a7ad389ead4ae41af3d4cb8193aac1f9230857a303709e3012a98da141fcefaee657a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
